// <auto-generated />
using System;
using MeerJager.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeerJager.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("MeerJager.Data.Database.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("MeerJager.Data.Database.Name", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShipID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShipID");

                    b.ToTable("Names");
                });

            modelBuilder.Entity("MeerJager.Data.Database.Range", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Min")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Range");
                });

            modelBuilder.Entity("MeerJager.Data.Database.Ship", b =>
                {
                    b.Property<int>("ShipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HealthId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShipID");

                    b.HasIndex("ClassId");

                    b.HasIndex("HealthId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("MeerJager.Data.Database.Name", b =>
                {
                    b.HasOne("MeerJager.Data.Database.Ship", null)
                        .WithMany("Names")
                        .HasForeignKey("ShipID");
                });

            modelBuilder.Entity("MeerJager.Data.Database.Ship", b =>
                {
                    b.HasOne("MeerJager.Data.Database.Class", "Class")
                        .WithMany("Ships")
                        .HasForeignKey("ClassId");

                    b.HasOne("MeerJager.Data.Database.Range", "Health")
                        .WithMany()
                        .HasForeignKey("HealthId");

                    b.HasOne("MeerJager.Data.Database.Range", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");
                });
#pragma warning restore 612, 618
        }
    }
}
